/*

NUMBER GUESSING GAME

write a program in JAVA to create a number guessing game which is fun and easy project that allows a user
to guess the number generated by the computer and involves the following steps.
	1. the system generates a random number from a given range (1 to 100)
	2. the user is prompted to enter their given number in a displayed dialogue box.
	3. the computer then tells if the entered number matches the guesses number or
	   it is higher/lower than the generated number.
	4. the game continues under the user guessing the number.

 */

import java.util.Random;
import java.util.Scanner;

public class task_2 {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        Random random = new Random();

        int lowerBound = 1;
        int upperBound = 100;
        int targetNumber = random.nextInt(upperBound - lowerBound + 1) + lowerBound;

        System.out.println("Welcome to the Number Guessing Game!");
        System.out.println("I've picked a number between " + lowerBound + " and " + upperBound + ". Try to guess it!");

        int attempts = 0;
        int userGuess;

        do {
            System.out.print("Enter your guess: ");
            userGuess = sc.nextInt();
            attempts++;

            if (userGuess == targetNumber) {
                System.out.println("Congratulations! You guessed it right in " + attempts + " attempts.");
            } else if (userGuess < targetNumber) {
                System.out.println("Try a higher number.");
            } else {
                System.out.println("Try a lower number.");
            }
        } while (userGuess != targetNumber);

        sc.close();
    }
}
